# Generated by Django 5.1.5 on 2025-03-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='historic_site_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='historic_site_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='restaurant_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='restaurant_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
