# Generated by Django 5.1.5 on 2025-03-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_story_historic_site_name_story_historic_site_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='food_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='food_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='historic_site_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
