# Generated by Django 5.1.5 on 2025-04-16 05:48

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_story_food_description_story_food_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='story_covers/', validators=[core.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', validators=[core.models.validate_file_size]),
        ),
    ]
